# Generated by Django 3.2.6 on 2021-08-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='modified_ad',
            new_name='modified_at',
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('lost', 'Lost'), ('won', 'Won'), ('contacted', 'Contacted'), ('inprogress', 'In Progress')], default='new', max_length=25),
        ),
    ]
